// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtt8SFGPKcOFmJe69Qgj5fpm_-YiMd5k',
    appId: '1:561685697336:web:7dc2a3904b23495edd67cd',
    messagingSenderId: '561685697336',
    projectId: 'waitronapp',
    authDomain: 'waitronapp.firebaseapp.com',
    storageBucket: 'waitronapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ91tlVFt487Lg5eZhTAzsDyn1MMz2FIk',
    appId: '1:561685697336:android:6b28274e1c088a1fdd67cd',
    messagingSenderId: '561685697336',
    projectId: 'waitronapp',
    storageBucket: 'waitronapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuwXNhqEccGfbpXaBQGg3TTA6UxLqGOXU',
    appId: '1:561685697336:ios:cb77cdb10caae286dd67cd',
    messagingSenderId: '561685697336',
    projectId: 'waitronapp',
    storageBucket: 'waitronapp.appspot.com',
    iosBundleId: 'com.example.waitronApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuwXNhqEccGfbpXaBQGg3TTA6UxLqGOXU',
    appId: '1:561685697336:ios:51ffbe0c8437b207dd67cd',
    messagingSenderId: '561685697336',
    projectId: 'waitronapp',
    storageBucket: 'waitronapp.appspot.com',
    iosBundleId: 'com.example.waitronApp.RunnerTests',
  );
}
